# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'USFaceEnroll' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ATBaseExtensions', :git => 'https://github.com/ATiOSModule/ATBaseExtensions.git', :tag => '0.0.2'
  pod 'ATFaceDetectCamera', :git => 'https://github.com/ATiOSModule/ATFaceDetectCamera.git', :tag => '0.0.3'
  pod 'Alamofire'

end
